/**
* Banafshe Bamdad 
* Mo Jul 3, 2023 11:54:27 CET
* This script get the reprojection error estimated by Kalibr, 
* and compute an average projection error.
* I calculated the mean of absolute values of the reprojection values. 
* I assumed that the reprojection errors are in the same unit.
* I got the reprojection errors from the following file generated by Kalibr:
* /media/banafshe/Banafshe_2TB/calibration/Kalibr/my_calibration_RPG_D435i/distortion_model_equidistant/RPG_D435i_calibration-results-cam.txt
*/

#include <iostream>

double convertToAvgReprojectionError(double errorX, double errorY) {
    return (std::abs(errorX) + std::abs(errorY)) / 2.0;
}

int main() {
    // Kalibr: reprojection error: [-0.000876, -0.000251] +- [0.461041, 0.396340]
    double errorX = -0.000876;
    double errorY = -0.000251;
    
    double avgReprojectionError = convertToAvgReprojectionError(errorX, errorY);
    
    std::cout << "Average Reprojection Error: " << avgReprojectionError << std::endl;
    
    return 0;
}
